<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            // Pizza & Panini del Gusto
            ['name' => 'Margherita', 'ingredients' => 'Pomodoro, Mozzarella, Basilico', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/92d956ee3f1d2039cea29ac831305d04b49f7e91/margherita.jpg'],
            ['name' => 'Diavola', 'ingredients' => 'Pomodoro, Mozzarella, Salame Piccante', 'price' => 6.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/92d956ee3f1d2039cea29ac831305d04b49f7e91/pizza_prosciutto.jpg'],
            ['name' => 'Capricciosa', 'ingredients' => 'Pomodoro, Mozzarella, Funghi, Prosciutto, Carciofi', 'price' => 7.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/92d956ee3f1d2039cea29ac831305d04b49f7e91/capricciosa.jpg'],
            ['name' => 'Quattro Stagioni', 'ingredients' => 'Pomodoro, Mozzarella, Funghi, Prosciutto, Olive, Carciofi', 'price' => 7.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/92d956ee3f1d2039cea29ac831305d04b49f7e91/quattro_stagioni.jpg'],
            ['name' => 'Panino Classico', 'ingredients' => 'Prosciutto, Formaggio, Insalata', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/92d956ee3f1d2039cea29ac831305d04b49f7e91/panino_classico.jpg'],
            ['name' => 'Panino con Tonno', 'ingredients' => 'Tonno, Pomodoro, Insalata', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/92d956ee3f1d2039cea29ac831305d04b49f7e91/panino_tonno.jpg'],
            ['name' => 'Panino Vegetariano', 'ingredients' => 'Verdure Grigliate, Formaggio, Salsa', 'price' => 5.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/92d956ee3f1d2039cea29ac831305d04b49f7e91/panino_vegetariano.jpg'],
            ['name' => 'Pizza al Prosciutto', 'ingredients' => 'Pomodoro, Mozzarella, Prosciutto Cotto', 'price' => 6.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/92d956ee3f1d2039cea29ac831305d04b49f7e91/pizza_prosciutto.jpg'],
            ['name' => 'Pizza ai Funghi', 'ingredients' => 'Pomodoro, Mozzarella, Funghi', 'price' => 6.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/92d956ee3f1d2039cea29ac831305d04b49f7e91/pizza_funghi.jpg'],
            ['name' => 'Pizza Quattro Formaggi', 'ingredients' => 'Mozzarella, Gorgonzola, Parmigiano, Fontina', 'price' => 7.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/92d956ee3f1d2039cea29ac831305d04b49f7e91/pizza_quattro_formaggi.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // FastBite
            ['name' => 'Cheeseburger', 'ingredients' => 'Manzo, Formaggio, Insalata, Pomodoro, Salsa', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 2, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/cheeseburger.jpg'],
            ['name' => 'Hamburger Classico', 'ingredients' => 'Manzo, Insalata, Pomodoro, Salsa', 'price' => 3.50, 'visible' => true, 'restaurant_id' => 2, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/hamburger_classico.jpg'],
            ['name' => 'Chicken Nuggets', 'ingredients' => 'Pollo, Panatura, Salsa', 'price' => 3.00, 'visible' => true, 'restaurant_id' => 2, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/chicken_nuggets.jpg'],
            ['name' => 'Patatine Fritte', 'ingredients' => 'Patate, Sale', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 2, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/patatine_fritte.jpg'],
            ['name' => 'Hot Dog', 'ingredients' => 'Wurstel, Pane, Salsa, Cipolla', 'price' => 3.00, 'visible' => true, 'restaurant_id' => 2, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/hot_dog.jpg'],
            ['name' => 'Fish and Chips', 'ingredients' => 'Merluzzo, Patate, Salsa', 'price' => 6.00, 'visible' => true, 'restaurant_id' => 2, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/fish_and_chips.jpg'],
            ['name' => 'Panino con Pollo', 'ingredients' => 'Pollo, Insalata, Pomodoro, Salsa', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 2, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/chickenburger.jpg'],
            ['name' => 'Milkshake', 'ingredients' => 'Latte, Gelato, Zucchero', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 2, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/milkshake.jpg'],
            ['name' => 'Chickenburger', 'ingredients' => 'Pollo, Insalata, Pomodoro, Salsa', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 2, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/chickenburger.jpg'],
            ['name' => 'Double Cheeseburger', 'ingredients' => 'Doppio Manzo, Doppio Formaggio, Insalata, Pomodoro, Salsa', 'price' => 5.00, 'visible' => true, 'restaurant_id' => 2, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/double_cheeseburger.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // BelaVita
            ['name' => 'Spaghetti alla Carbonara', 'ingredients' => 'Spaghetti, Uova, Pancetta, Pecorino', 'price' => 7.50, 'visible' => true, 'restaurant_id' => 3, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/fac70f9740fa965fd2656616aa5eee6aa195bf6e/spaghetti_carbonara.jpg'],
            ['name' => 'Lasagna', 'ingredients' => 'Pasta, Ragù, Besciamella, Parmigiano', 'price' => 8.00, 'visible' => true, 'restaurant_id' => 3, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/lasagna.jpg'],
            ['name' => 'Risotto ai Funghi', 'ingredients' => 'Riso, Funghi, Parmigiano', 'price' => 7.00, 'visible' => true, 'restaurant_id' => 3, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/fac70f9740fa965fd2656616aa5eee6aa195bf6e/risotto_funghi.jpg'],
            ['name' => 'Gnocchi alla Sorrentina', 'ingredients' => 'Gnocchi, Pomodoro, Mozzarella, Basilico', 'price' => 6.50, 'visible' => true, 'restaurant_id' => 3, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/fac70f9740fa965fd2656616aa5eee6aa195bf6e/gnocchi_sorrentina.jpg'],
            ['name' => 'Tiramisù', 'ingredients' => 'Mascarpone, Caffè, Savoiardi, Cacao', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 3, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/fac70f9740fa965fd2656616aa5eee6aa195bf6e/tiramisu.jpg'],
            ['name' => 'Panna Cotta', 'ingredients' => 'Panna, Zucchero, Vaniglia', 'price' => 3.50, 'visible' => true, 'restaurant_id' => 3, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/fac70f9740fa965fd2656616aa5eee6aa195bf6e/panna_cotta.jpg'],
            ['name' => 'Pizza Margherita', 'ingredients' => 'Pomodoro, Mozzarella, Basilico', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 3, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/fac70f9740fa965fd2656616aa5eee6aa195bf6e/margherita.jpg'],
            ['name' => 'Pizza Diavola', 'ingredients' => 'Pomodoro, Mozzarella, Salame Piccante', 'price' => 6.50, 'visible' => true, 'restaurant_id' => 3, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/fac70f9740fa965fd2656616aa5eee6aa195bf6e/diavola.jpg'],
            ['name' => 'Pizza Quattro Formaggi', 'ingredients' => 'Mozzarella, Gorgonzola, Parmigiano, Fontina', 'price' => 7.00, 'visible' => true, 'restaurant_id' => 3, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/fac70f9740fa965fd2656616aa5eee6aa195bf6e/pizza_quattro_formaggi.jpg'],
            ['name' => 'Tagliatelle al Ragù', 'ingredients' => 'Tagliatelle, Ragù di Carne, Parmigiano', 'price' => 7.50, 'visible' => true, 'restaurant_id' => 3, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/fac70f9740fa965fd2656616aa5eee6aa195bf6e/tagliatelle_ragu.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // Grill & Wrap
            ['name' => 'Hamburger con Bacon', 'ingredients' => 'Manzo, Bacon, Formaggio, Insalata, Pomodoro, Salsa', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 4, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f5877f4510601c70ddf9001fbc0749533dac07b7/hamburger_bacon.jpg'],
            ['name' => 'Cheeseburger', 'ingredients' => 'Manzo, Formaggio, Insalata, Pomodoro, Salsa', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 4, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/7a8216c616baa149370a63278c2b79d013b49a6e/cheeseburger.jpg'],
            ['name' => 'Wrap con Pollo', 'ingredients' => 'Pollo, Insalata, Pomodoro, Salsa', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 4, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f5877f4510601c70ddf9001fbc0749533dac07b7/wrap_pollo.jpg'],
            ['name' => 'Wrap Vegetariano', 'ingredients' => 'Verdure Grigliate, Formaggio, Salsa', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 4, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f5877f4510601c70ddf9001fbc0749533dac07b7/wrap_vegetariano.jpg'],
            ['name' => 'Piadina con Prosciutto', 'ingredients' => 'Prosciutto, Formaggio, Rucola', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 4, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f5877f4510601c70ddf9001fbc0749533dac07b7/piadina_prosciutto.jpg'],
            ['name' => 'Piadina Vegetariana', 'ingredients' => 'Verdure Grigliate, Formaggio, Salsa', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 4, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f5877f4510601c70ddf9001fbc0749533dac07b7/piadina_vegetariana.jpg'],
            ['name' => 'Hamburger Classico', 'ingredients' => 'Manzo, Insalata, Pomodoro, Salsa', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 4, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f5877f4510601c70ddf9001fbc0749533dac07b7/hamburger_classico.jpg'],
            ['name' => 'Piadina con Salsiccia', 'ingredients' => 'Salsiccia, Formaggio, Insalata', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 4, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f5877f4510601c70ddf9001fbc0749533dac07b7/piadina_salsiccia.jpg'],
            ['name' => 'Panino con Prosciutto e Formaggio', 'ingredients' => 'Prosciutto, Formaggio, Insalata', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 4, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f5877f4510601c70ddf9001fbc0749533dac07b7/panino_prosciutto_formaggio.jpg'],
            ['name' => 'Panino con Tonno', 'ingredients' => 'Tonno, Pomodoro, Insalata', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 4, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f5877f4510601c70ddf9001fbc0749533dac07b7/panino_tonno.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // Waggshii
            ['name' => 'Sushi Misto', 'ingredients' => 'Riso, Pesce Misto, Alga', 'price' => 8.50, 'visible' => true, 'restaurant_id' => 5, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/sushi_misto.jpg'],
            ['name' => 'Sashimi di Salmone', 'ingredients' => 'Salmone Crudo', 'price' => 9.00, 'visible' => true, 'restaurant_id' => 5, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/sashimi_salmone.jpg'],
            ['name' => 'Nigiri', 'ingredients' => 'Riso, Pesce Crudo', 'price' => 7.50, 'visible' => true, 'restaurant_id' => 5, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/nigiri.jpg'],
            ['name' => 'Tempura di Gamberi', 'ingredients' => 'Gamberi, Pastella, Salsa', 'price' => 6.50, 'visible' => true, 'restaurant_id' => 5, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/tempura_gamberi.jpg'],
            ['name' => 'Involtini Primavera', 'ingredients' => 'Verdure, Pasta Filló', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 5, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/involtini_primavera.jpg'],
            ['name' => 'Ravioli al Vapore', 'ingredients' => 'Carne, Verdure, Salsa di Soia', 'price' => 5.00, 'visible' => true, 'restaurant_id' => 5, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/ravioli_vapore.jpg'],
            ['name' => 'Uramaki', 'ingredients' => 'Riso, Pesce Crudo, Alga', 'price' => 7.50, 'visible' => true, 'restaurant_id' => 5, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/uramaki.jpg'],
            ['name' => 'Zuppa di Miso', 'ingredients' => 'Tofu, Alga, Miso', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 5, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/zuppa_miso.jpg'],
            ['name' => 'Riso alla Cantonese', 'ingredients' => 'Riso, Uova, Verdure, Prosciutto', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 5, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/ravioli_vapore.jpg'],
            ['name' => 'Soba', 'ingredients' => 'Spaghetti di Grano Saraceno, Verdure', 'price' => 6.00, 'visible' => true, 'restaurant_id' => 5, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/soba.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // Gelato d'Amore
            ['name' => 'Gelato alla Vaniglia', 'ingredients' => 'Latte, Zucchero, Vaniglia', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 6, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f8691f49ea01eba09822058d2ea8a801eb25c3eb/gelato_vaniglia.jpg'],
            ['name' => 'Gelato al Cioccolato', 'ingredients' => 'Latte, Zucchero, Cioccolato', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 6, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f8691f49ea01eba09822058d2ea8a801eb25c3eb/gelato_cioccolato.jpg'],
            ['name' => 'Gelato alla Fragola', 'ingredients' => 'Latte, Zucchero, Fragole', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 6, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f8691f49ea01eba09822058d2ea8a801eb25c3eb/gelato_fragola.jpg'],
            ['name' => 'Gelato al Pistacchio', 'ingredients' => 'Latte, Zucchero, Pistacchi', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 6, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f8691f49ea01eba09822058d2ea8a801eb25c3eb/gelato_pistacchio.jpg'],
            ['name' => 'Gelato al Limone', 'ingredients' => 'Latte, Zucchero, Limoni', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 6, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f8691f49ea01eba09822058d2ea8a801eb25c3eb/gelato_limone.jpg'],
            ['name' => 'Gelato alla Nocciola', 'ingredients' => 'Latte, Zucchero, Nocciole', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 6, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f8691f49ea01eba09822058d2ea8a801eb25c3eb/gelato_nocciola.jpg'],
            ['name' => 'Gelato allo Yogurt', 'ingredients' => 'Latte, Zucchero, Yogurt', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 6, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f8691f49ea01eba09822058d2ea8a801eb25c3eb/gelato_yogurt.jpg'],
            ['name' => 'Coppa Fragole e Panna', 'ingredients' => 'Fragole, Panna Montata, Zucchero', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 6, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f8691f49ea01eba09822058d2ea8a801eb25c3eb/coppa_fragole_panna.jpg'],
            ['name' => 'Coppa Cioccolato e Nocciola', 'ingredients' => 'Gelato al Cioccolato, Gelato alla Nocciola, Panna Montata', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 6, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f8691f49ea01eba09822058d2ea8a801eb25c3eb/coppa_cioccolato_nocciola.jpg'],
            ['name' => 'Banana Split', 'ingredients' => 'Banane, Gelato alla Vaniglia, Gelato al Cioccolato, Panna Montata, Cioccolato Fuso', 'price' => 5.00, 'visible' => true, 'restaurant_id' => 6, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f8691f49ea01eba09822058d2ea8a801eb25c3eb/banana_split.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // Kebab e Pizza King
            ['name' => 'Kebab Classico', 'ingredients' => 'Carne di Manzo, Insalata, Pomodoro, Cipolla, Salsa', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 7, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/5b79c2dcb49f675856d57dd6cd05eb6a9d1bce2f/kebab_classico.jpg'],
            ['name' => 'Kebab con Pollo', 'ingredients' => 'Carne di Pollo, Insalata, Pomodoro, Cipolla, Salsa', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 7, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/5b79c2dcb49f675856d57dd6cd05eb6a9d1bce2f/kebab_pollo.jpg'],
            ['name' => 'Kebab con Verdure', 'ingredients' => 'Verdure Grigliate, Insalata, Pomodoro, Cipolla, Salsa', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 7, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/5b79c2dcb49f675856d57dd6cd05eb6a9d1bce2f/kebab_verdure.jpg'],
            ['name' => 'Pizza Margherita', 'ingredients' => 'Pomodoro, Mozzarella, Basilico', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 7, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/5b79c2dcb49f675856d57dd6cd05eb6a9d1bce2f/margherita.jpg'],
            ['name' => 'Pizza Diavola', 'ingredients' => 'Pomodoro, Mozzarella, Salame Piccante', 'price' => 6.50, 'visible' => true, 'restaurant_id' => 7, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/fac70f9740fa965fd2656616aa5eee6aa195bf6e/diavola.jpg'],
            ['name' => 'Pizza Quattro Formaggi', 'ingredients' => 'Mozzarella, Gorgonzola, Parmigiano, Fontina', 'price' => 7.00, 'visible' => true, 'restaurant_id' => 7, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/5b79c2dcb49f675856d57dd6cd05eb6a9d1bce2f/pizza_quattro_formaggi.jpg'],
            ['name' => 'Panino con Prosciutto', 'ingredients' => 'Prosciutto, Formaggio, Insalata', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 7, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/5b79c2dcb49f675856d57dd6cd05eb6a9d1bce2f/panino_prosciutto.jpg'],
            ['name' => 'Panino Vegetariano', 'ingredients' => 'Verdure Grigliate, Formaggio, Salsa', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 7, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/5b79c2dcb49f675856d57dd6cd05eb6a9d1bce2f/panino_vegetariano.jpg'],
            ['name' => 'Kebab Special', 'ingredients' => 'Carne di Manzo, Pollo, Insalata, Pomodoro, Cipolla, Salsa', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 7, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/5b79c2dcb49f675856d57dd6cd05eb6a9d1bce2f/kebab_special.jpg'],
            ['name' => 'Falafel', 'ingredients' => 'Polpette di Ceci, Insalata, Pomodoro, Cipolla, Salsa', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 7, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/5b79c2dcb49f675856d57dd6cd05eb6a9d1bce2f/falafel.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // El Sombrero Mexicano
            ['name' => 'Tacos al Pastor', 'ingredients' => 'Carne di Maiale, Ananas, Cipolla, Salsa', 'price' => 5.00, 'visible' => true, 'restaurant_id' => 8, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/d37e7220dc04cbe1716e10f83e0aee7a3453012f/tacos_al_pastor.jpg'],
            ['name' => 'Burrito con Carne', 'ingredients' => 'Carne di Manzo, Fagioli, Riso, Salsa', 'price' => 6.50, 'visible' => true, 'restaurant_id' => 8, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/d37e7220dc04cbe1716e10f83e0aee7a3453012f/burrito_carne.jpg'],
            ['name' => 'Enchiladas', 'ingredients' => 'Tortillas, Salsa, Formaggio, Carne', 'price' => 6.00, 'visible' => true, 'restaurant_id' => 8, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/d37e7220dc04cbe1716e10f83e0aee7a3453012f/enchiladas.jpg'],
            ['name' => 'Quesadillas', 'ingredients' => 'Tortilla, Formaggio, Carne, Verdure', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 8, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/d37e7220dc04cbe1716e10f83e0aee7a3453012f/quesadillas.jpg'],
            ['name' => 'Guacamole', 'ingredients' => 'Avocado, Cipolla, Lime, Pomodoro', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 8, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/d37e7220dc04cbe1716e10f83e0aee7a3453012f/guacamole.jpg'],
            ['name' => 'Nachos con Formaggio', 'ingredients' => 'Nachos, Formaggio, Salsa', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 8, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/d37e7220dc04cbe1716e10f83e0aee7a3453012f/nachos_formaggio.jpg'],
            ['name' => 'Churros', 'ingredients' => 'Farina, Zucchero, Cannella', 'price' => 3.50, 'visible' => true, 'restaurant_id' => 8, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/d37e7220dc04cbe1716e10f83e0aee7a3453012f/churros.jpg'],
            ['name' => 'Fajitas di Pollo', 'ingredients' => 'Pollo, Peperoni, Cipolla, Tortillas', 'price' => 6.50, 'visible' => true, 'restaurant_id' => 8, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/d37e7220dc04cbe1716e10f83e0aee7a3453012f/fajitas_pollo.jpg'],
            ['name' => 'Tacos di Pesce', 'ingredients' => 'Pesce, Insalata, Salsa, Lime', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 8, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/d37e7220dc04cbe1716e10f83e0aee7a3453012f/tacos_pesce.jpg'],
            ['name' => 'Salsa Piccante', 'ingredients' => 'Pomodoro, Peperoncino, Cipolla', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 8, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/d37e7220dc04cbe1716e10f83e0aee7a3453012f/salsa_piccante.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // La Cina in Tavola
            ['name' => 'Ravioli al Vapore', 'ingredients' => 'Carne, Verdure, Salsa di Soia', 'price' => 5.00, 'visible' => true, 'restaurant_id' => 9, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/ravioli_vapore.jpg'],
            ['name' => 'Involtini Primavera', 'ingredients' => 'Verdure, Pasta Filló', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 9, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/involtini_primavera.jpg'],
            ['name' => 'Riso alla Cantonese', 'ingredients' => 'Riso, Uova, Verdure, Prosciutto', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 9, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/riso_cantonese.jpg'],
            ['name' => 'Zuppa di Miso', 'ingredients' => 'Tofu, Alga, Miso', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 9, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/zuppa_miso.jpg'],
            ['name' => 'Soba', 'ingredients' => 'Spaghetti di Grano Saraceno, Verdure', 'price' => 6.00, 'visible' => true, 'restaurant_id' => 9, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/soba.jpg'],
            ['name' => 'Tempura di Gamberi', 'ingredients' => 'Gamberi, Pastella, Salsa', 'price' => 6.50, 'visible' => true, 'restaurant_id' => 9, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/tempura_gamberi.jpg'],
            ['name' => 'Peking Duck', 'ingredients' => 'Anatra, Pancake, Salsa Hoisin', 'price' => 12.00, 'visible' => true, 'restaurant_id' => 9, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/peking_duck.jpg'],
            ['name' => 'Kung Pao Chicken', 'ingredients' => 'Pollo, Peperoni, Anacardi, Salsa', 'price' => 7.50, 'visible' => true, 'restaurant_id' => 9, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/kung_pao_chicken.jpg'],
            ['name' => 'Riso Fritto', 'ingredients' => 'Riso, Uova, Verdure, Salsa di Soia', 'price' => 5.00, 'visible' => true, 'restaurant_id' => 9, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/riso_fritto.jpg'],
            ['name' => 'Moo Shu Pork', 'ingredients' => 'Maiale, Pancake, Verdure, Salsa', 'price' => 7.00, 'visible' => true, 'restaurant_id' => 9, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/moo_shu_pork.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // Burger Express
            ['name' => 'Cheeseburger', 'ingredients' => 'Manzo, Formaggio, Insalata, Pomodoro, Salsa', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 10, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/912e4d09f7632ea3824c22040f25dbed949a06e6/cheeseburger.jpg'],
            ['name' => 'Hamburger Classico', 'ingredients' => 'Manzo, Insalata, Pomodoro, Salsa', 'price' => 3.50, 'visible' => true, 'restaurant_id' => 10, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/912e4d09f7632ea3824c22040f25dbed949a06e6/hamburger_classico.jpg'],
            ['name' => 'Chicken Nuggets', 'ingredients' => 'Pollo, Panatura, Salsa', 'price' => 3.00, 'visible' => true, 'restaurant_id' => 10, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/912e4d09f7632ea3824c22040f25dbed949a06e6/chicken_nuggets.jpg'],
            ['name' => 'Patatine Fritte', 'ingredients' => 'Patate, Sale', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 10, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/912e4d09f7632ea3824c22040f25dbed949a06e6/patatine_fritte.jpg'],
            ['name' => 'Hot Dog', 'ingredients' => 'Wurstel, Pane, Salsa, Cipolla', 'price' => 3.00, 'visible' => true, 'restaurant_id' => 10, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/912e4d09f7632ea3824c22040f25dbed949a06e6/hot_dog.jpg'],
            ['name' => 'Fish and Chips', 'ingredients' => 'Merluzzo, Patate, Salsa', 'price' => 6.00, 'visible' => true, 'restaurant_id' => 10, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/912e4d09f7632ea3824c22040f25dbed949a06e6/fish_and_chips.jpg'],
            ['name' => 'Panino con Pollo', 'ingredients' => 'Pollo, Insalata, Pomodoro, Salsa', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 10, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/912e4d09f7632ea3824c22040f25dbed949a06e6/panino_pollo.jpg'],
            ['name' => 'Milkshake', 'ingredients' => 'Latte, Gelato, Zucchero', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 10, 'type' => 'Dessert', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/912e4d09f7632ea3824c22040f25dbed949a06e6/milkshake.jpg'],
            ['name' => 'Chickenburger', 'ingredients' => 'Pollo, Insalata, Pomodoro, Salsa', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 10, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/912e4d09f7632ea3824c22040f25dbed949a06e6/chickenburger.jpg'],
            ['name' => 'Onion Rings', 'ingredients' => 'Anelli di Cipolla, Panatura', 'price' => 2.50, 'visible' => true, 'restaurant_id' => 10, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/912e4d09f7632ea3824c22040f25dbed949a06e6/onion_rings.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // Sushi Sensation
            ['name' => 'Sushi Misto', 'ingredients' => 'Riso, Pesce Misto, Alga', 'price' => 8.50, 'visible' => true, 'restaurant_id' => 11, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/111f54182e8e4d66a44967367adcbf3d8c0aba89/sushi_misto.jpg'],
            ['name' => 'Sashimi di Salmone', 'ingredients' => 'Salmone Crudo', 'price' => 9.00, 'visible' => true, 'restaurant_id' => 11, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/bf886ec1ff95d45dce1b1de0510c231648dc1ffb/sashimi_salmone.jpg'],
            ['name' => 'Nigiri', 'ingredients' => 'Riso, Pesce Crudo', 'price' => 7.50, 'visible' => true, 'restaurant_id' => 11, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/bf886ec1ff95d45dce1b1de0510c231648dc1ffb/nigiri.jpg'],
            ['name' => 'Uramaki', 'ingredients' => 'Riso, Pesce Crudo, Alga', 'price' => 7.50, 'visible' => true, 'restaurant_id' => 11, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/bf886ec1ff95d45dce1b1de0510c231648dc1ffb/uramaki.jpg'],
            ['name' => 'Zuppa di Miso', 'ingredients' => 'Tofu, Alga, Miso', 'price' => 4.50, 'visible' => true, 'restaurant_id' => 11, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/bf886ec1ff95d45dce1b1de0510c231648dc1ffb/zuppa_miso.jpg'],
            ['name' => 'Sushi alla Griglia', 'ingredients' => 'Pesce, Riso, Salsa', 'price' => 9.00, 'visible' => true, 'restaurant_id' => 11, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/bf886ec1ff95d45dce1b1de0510c231648dc1ffb/sushi_griglia.jpg'],
            ['name' => 'Tempura di Gamberi', 'ingredients' => 'Gamberi, Pastella, Salsa', 'price' => 6.50, 'visible' => true, 'restaurant_id' => 11, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/bf886ec1ff95d45dce1b1de0510c231648dc1ffb/tempura_gamberi.jpg'],
            ['name' => 'Involtini Primavera', 'ingredients' => 'Verdure, Pasta Filló', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 11, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/ad631f52fbfc472db0c761098fa5fb9984cb99cb/involtini_primavera.jpg'],
            ['name' => 'Ravioli al Vapore', 'ingredients' => 'Carne, Verdure, Salsa di Soia', 'price' => 5.00, 'visible' => true, 'restaurant_id' => 11, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/bf886ec1ff95d45dce1b1de0510c231648dc1ffb/ravioli_vapore.jpg'],
            ['name' => 'Riso alla Cantonese', 'ingredients' => 'Riso, Uova, Verdure, Prosciutto', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 11, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/bf886ec1ff95d45dce1b1de0510c231648dc1ffb/riso_cantonese.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

            // Bella Pizza e Cucina
            ['name' => 'Pizza Margherita', 'ingredients' => 'Pomodoro, Mozzarella, Basilico', 'price' => 5.50, 'visible' => true, 'restaurant_id' => 12, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/margherita.jpg'],
            ['name' => 'Pizza Quattro Stagioni', 'ingredients' => 'Pomodoro, Mozzarella, Prosciutto, Funghi, Carciofi, Olive', 'price' => 7.00, 'visible' => true, 'restaurant_id' => 12, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/pizza_quattro_stagioni.jpg'],
            ['name' => 'Pizza Capricciosa', 'ingredients' => 'Pomodoro, Mozzarella, Prosciutto, Funghi, Carciofi', 'price' => 6.50, 'visible' => true, 'restaurant_id' => 12, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/pizza_capricciosa.jpg'],
            ['name' => 'Pizza Napoli', 'ingredients' => 'Pomodoro, Mozzarella, Acciughe, Capperi', 'price' => 6.00, 'visible' => true, 'restaurant_id' => 12, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/pizza_napoli.jpg'],
            ['name' => 'Pasta Carbonara', 'ingredients' => 'Pasta, Uova, Pancetta, Formaggio', 'price' => 7.00, 'visible' => true, 'restaurant_id' => 12, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/pasta_carbonara.jpg'],
            ['name' => 'Lasagna', 'ingredients' => 'Pasta, Carne Macinata, Besciamella, Formaggio', 'price' => 8.00, 'visible' => true, 'restaurant_id' => 12, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/lasagna.jpg'],
            ['name' => 'Spaghetti al Pomodoro', 'ingredients' => 'Spaghetti, Pomodoro, Basilico, Olio d\'Oliva', 'price' => 6.00, 'visible' => true, 'restaurant_id' => 12, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/spaghetti_pomodoro.jpg'],
            ['name' => 'Bruschetta', 'ingredients' => 'Pane, Pomodoro, Basilico, Olio d\'Oliva', 'price' => 4.00, 'visible' => true, 'restaurant_id' => 12, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/bruschetta.jpg'],
            ['name' => 'Tiramisu', 'ingredients' => 'Mascarpone, Caffè, Savoiardi, Cacao', 'price' => 5.00, 'visible' => true, 'restaurant_id' => 12, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/tiramisu.jpg'],
            ['name' => 'Panna Cotta', 'ingredients' => 'Panna, Zucchero, Gelatina, Salsa di Frutta', 'price' => 5.00, 'visible' => true, 'restaurant_id' => 12, 'type' => 'Food', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/6f7ee97eb1fcfaf14c6b74fcd5e3f9c35cfa39f6/panna_cotta.jpg'],
            ['name' => 'Coca-Cola', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/coca-cola.jpg'],
            ['name' => 'Fanta', 'ingredients' => null, 'price' => 2.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/fanta.jpg'],
            ['name' => 'Birra', 'ingredients' => null, 'price' => 3.50, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bevande Alcoliche', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/birra.jpg'],
            ['name' => 'Acqua', 'ingredients' => null, 'price' => 1.00, 'visible' => true, 'restaurant_id' => 1, 'type' => 'Bibite', 'image_path' => 'https://raw.githubusercontent.com/davidearbola/prod-img-deliveboo/f6ca304c3c2754d6111e86771f7965daf333fbf9/acqua.jpg'],

        ]);
    }
}
